#!/usr/bin/env ruby
require 'yaml'
require 'mongo'

CNAES = YAML.load_file('readable/cnaes.yml')
CBOS = YAML.load_file('readable/cbos.yml')

DB = ARGV.join

fail 'Please provide a DB' if DB.empty?

p "Restoring data to #{DB}"
c = Mongo::Client.new(['127.0.0.1:27017'], :database => DB)
trades = c[:trades]
profs = c[:professions]

puts
puts 'CNAES'
CNAES.each do |k, v|
  if trades.find(_id: k)
    trades.find(_id: k).replace_one(name: v)
  else
    trades.insert_one({ _id: k, name: v })
  end
end


puts
puts 'CBOS'
CNAES.each do |k, v|
  if profs.find(_id: k)
    profs.find(_id: k).replace_one(name: v)
  else
    profs.insert_one({ _id: k, name: v })
  end
end
